### ISSUE TITLE
GunningFogIndex

### ISSUE THREAD

**Issue by bhashithe** [andreasvc/readability#8]
This is more of a question related to where I would be able to find the literature for this index. Probably I am not looking at the proper place for this. Please be kind enough to help me find the full-text :)

**Comment by andreasvc** [comment]
Have you tried Google Scholar? This seems to be it: https://files.eric.ed.gov/fulltext/ED014628.pdf

**Comment by bhashithe** [comment]
I've looked in google scholar but could not find the article that you linked above. Thank you so much! This helps a lot.
